Repro panic when `rv ruby run` with no version
If you don't have any Rubies installed, AND you use `rv ruby run` without a version, then rv panics.

```sh
$ rv ruby run -- -e 'puts "Hello, World"'
thread 'main' (52507175) panicked at crates/rv/src/commands/ruby/install.rs:119:49:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is because it passes RubyRequest::default() to the code that downloads a Ruby from rv-ruby, and there's no matching ruby for that.

The systematic problem here is that we use one type, RubyRequest, for two different purposes.